availability_zone  = "us-west-2c"
region             = "us-west-2"
instance_type      = "t2.micro"
ami_id		   = "ami-a07379d9"
iam_role	   = "s3access"
vpc_id 	           = "vpc-e9aac18d"
subnet_id          = "subnet-7915d421"
snapshot_id 	   = "snap-1bf4d897"
account		   = ""
created_by 	   = "J Foxx"
environment        = "Test"
key_name           = "jjj"
bucket		   = "sainsburys-test"

